modLoader = "javafml"
loaderVersion = "[43,)"
license = "LGPL-3.0-only"
issueTrackerURL = "https://github.com/SamsTheNerd/ducky-periphs/issues"
showAsResourcePack = false

[[mods]]
modId = "cobblecards"
version = "${mod_version}"
displayName = "CobbleCards"
displayURL = "https://github.com/SamsTheNerd/ducky-periphs"
logoFile = "icon.png"
authors = "samsthenerd"
description = "Adds cobblemon cards"

[[dependencies.cobblecards]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

  [[dependencies.cobblecards]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cobblecards]]
    modId="architectury"
    mandatory=true
    versionRange="[9.1.12,)"
    ordering="NONE"
    side="BOTH"
